# config/validator/validation.yaml

App\Entity\Location:
  properties:
    city:
      - NotBlank: { groups: ['create', 'edit'] }
      - Length:   { max: 255, groups: ['create', 'edit'] }
    country:
      - NotBlank: { groups: ['create', 'edit'] }
      
      - Choice:
          choices: ['PL', 'DE', 'FR', 'ES', 'IT', 'GB', 'US']
          groups:  ['create', 'edit']
    latitude:
      - NotBlank: { groups: ['create', 'edit'] }
      - Type:     { type: numeric, groups: ['create', 'edit'] }
      - Range:
          min:  -90
          max:  90
          groups: ['create', 'edit']
    longitude:
      - NotBlank: { groups: ['create', 'edit'] }
      - Type:     { type: numeric, groups: ['create', 'edit'] }
      - Range:
          min:  -180
          max:  180
          groups: ['create', 'edit']

App\Entity\Measurement:
  properties:
    date:
      - NotBlank: { groups: ['create', 'edit'] }
     
    celsius:
      - NotBlank: { groups: ['create', 'edit'] }
      - Type:     { type: numeric, groups: ['create', 'edit'] }
      - Range:
          min: -50
          max: 60
          groups: ['create', 'edit']
